[package]
name = "bloom-ws"
version = "0.1.0"
edition = "2021"

[dependencies]
bloom-api = { path = "../api" }
bloom-core = { path = "../core" }
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt", "sync"] }
